import { lighten, darken } from 'polished';
export const primary = '#f1c40f';
export const secondary = '#22a6b3';
export const secondaryDark = '#0c3c41';
export const secondaryLight = '#69d8e3';
export const danger = '#c0392b';
export const dark = '#1e2127';
export const light = '#ecf0f1';
export const darkenDark = darken(0.01, dark);
export const lightenDark = lighten(0.01, dark);
